// these are constants

export const GET_PRODUCTS_START = 'GET_PRODUCTS_START';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_FAILURE = 'GET_PRODUCTS_FAILURE';
export const ADD_ORDER_START = 'ADD_ORDER_START';
export const ADD_ORDER_SUCCES = 'ADD_ORDER_SUCCES';
export const ADD_ORDER_FAILURE = 'ADD_ORDER_FAILURE';
export const GET_ORDERS = 'GET_ORDERS';
export const EDIT_ORDER = 'EDIT_ORDER';
export const DELETE_ORDER = 'DELETE_ORDER';
export const ORDERS_LOADING = 'ORDERS_LOADING';
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
